services:
  data_api:
    build:
      context: ./data_api
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
        - "MIX_ENV=${MIX_ENV:-dev}"
        - "NODE_ENV=${NODE_ENV:-development}"
    ports:
      - "4000:4000"
    env_file:
      - ".env"
    volumes:
      - ./data_api:/app
    depends_on:
      - postgres
      - redis

  data_compiler:
    build:
      context: ./data_compiler
      dockerfile: Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
        - "MIX_ENV=${MIX_ENV:-dev}"
        - "NODE_ENV=${NODE_ENV:-development}"
    ports:
      - "4001:4000"
    env_file:
      - ".env"
    volumes:
      - ./data_compiler:/app
    depends_on:
      - redis

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sekret}
      POSTGRES_DB: ${POSTGRES_DB:-data_api_dev}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    env_file:
      - ".env"
    volumes:
      - ./frontend:/app
    depends_on:
      - data_api
      - data_compiler

volumes:
  postgres_data:
  redis_data:
